language: python
dist: xenial
sudo: false

env:
    global:
        - LMTPD_TEST_POST=9988

python:
    - pypy2.7-6.0
    - pypy3.5-6.0
    - "3.6"
    - "3.5"
    - "3.4"
    - "3.3"
    - "2.7"
    - "2.6"

script: "python setup.py test"
